---
- name: restart apache2
  ansible.builtin.service:
    name: apache2
    enabled: yes
    state: restarted

- name: restart httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: restarted
