---
- name: install mariadb on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ rocky_mariadb_packages }}"
  when: ansible_distribution == 'Rocky'

- name: install httpd packages on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ rocky_httpd_packages }}"
  when: ansible_distribution == 'Rocky'

- name: install PHP packages on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ rocky_php_packages }}"
  when: ansible_distribution == 'Rocky'