---
- name: install mariadb on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_mariadb_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install apache2 packages on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_apache2_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install PHP packages on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_php_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install redis on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_redis_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: Install file extraction tools on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_extract_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install imagemagick on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_imagemagick_packages }}"
  when: ansible_distribution == 'Ubuntu'
