---
- name: create nextcloud database on ubuntu
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    collation: utf8mb4_general_ci
    encoding: utf8mb4
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: create nextcloud database user on ubuntu
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    password: "{{ db_pass }}"
    priv: "*.*:USAGE/{{ db_name }}.*:ALL"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: create nextcloud database on rocky
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: ''
    collation: utf8mb4_general_ci
    encoding: utf8mb4
    state: present
  when: ansible_distribution == 'Rocky'

- name: create nextcloud database user on Rocky
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: ''
    host: "{{ db_host }}"
    password: "{{ db_pass }}"
    priv: "*.*:USAGE/{{ db_name }}.*:ALL"
    state: present
  when: ansible_distribution == 'Rocky'
