---
- name: Add host IP or FQDN to Nextcloud's trusted IPs
  lineinfile:
    path: "{{ nextcloud_data_dir }}/config/config.php"
    insertafter: "    0 =>"
    line: "    1 => '{{ server_name }}',"

- name: Add a default phone region
  lineinfile:
    path: "{{ nextcloud_data_dir }}/config/config.php"
    insertafter: "  'installed' => true,"
    line: "  'default_phone_region' => '{{ phone_region }}',"

- name: Junk folder cleanup
  lineinfile:
    path: "{{ nextcloud_data_dir }}/config/config.php"
    insertafter: "  'passwordsalt' =>"
    line: "  'skeletondirectory' => '/var/snap/nextcloud/common/nextcloud/data/ieskeleton',"

- name: Configure memcache using APcu
  lineinfile:
    path: "{{ nextcloud_data_dir }}/config/config.php"
    insertafter: " 'installed' => true,"
    line: "  'memcache.local' => '\\OC\\Memcache\\APCu',"

- name: Configure a maintenance window
  lineinfile:
    path: "{{ nextcloud_data_dir }}/config/config.php"
    insertafter: " 'installed' => true,"
    line: "  'maintenance_window_start' => 1,"

- name: Create cron job to run Nextcloud cron.php every 5 minutes on Rocky
  cron:
    name: Nextcloud Cron
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: "apache"
    job: "php82 -f {{ nextcloud_data_dir }}/cron.php"
  when: ansible_distribution == 'Rocky'

- name: Create cron job to run Nextcloud cron.php every 5 minutes on Ubuntu
  cron:
    name: Nextcloud Cron
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: "www-data"
    job: "php82 -f {{ nextcloud_data_dir }}/cron.php"
  when: ansible_distribution == 'Ubuntu'

