---
- name: Configure file locking using Redis
  blockinfile:
    path: /srv/nextcloud/config/config.php
    insertafter: " 'installed' => true,"
    marker: ""
    block: |
      // File Locking
        'filelocking.enabled' => true,
        'memcache.locking' => '\\OC\\Memcache\\Redis',
        'redis' =>
        array (
          'host' => 'localhost',
          'port' => 6379,
          'timeout' => 0.0,
          'password' => '',
        ),

- name: enable and start redis
  ansible.builtin.service:
    name: redis
    enabled: yes
    state: started
